version: "3"
services:
  db:
    image: "mongo:latest"
  graphql:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client/app
