version: "3"
services:
  db:
    image: "mongo:latest"
  nginx:
    restart: always
    build: ./nginx
    image: nreoch9/nextjs-graphql-auth-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - graphql
      - client
  graphql:
    build: ./server
    image: nreoch9/nextjs-graphql-auth-server:latest
    depends_on:
      - db
  client:
    build: ./client
    image: nreoch9/nextjs-graphql-auth-client:latest
